default_platform(:ios)

platform :ios do
  desc "iOS Firebase Distribution"
  lane :firebase_distribution do
    build_ios_app()

    firebase_app_distribution(
      app: options[:firebase_app_id],
      testers: "damsznajder@gmail.com"
    )
  end
end
