name: JS Lint & Unit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: yarn install

      - name: Lint
        run: |
          yarn lint
          yarn typescript

      - name: Tests
        run: yarn test:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV }}
          file: coverage/*
